version: "3.12"
services:
  db_auth:
    container_name: database_neo
    image: postgres:latest
    volumes:
      - db_auth_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "12345"

  web:
    container_name: web_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/backend_auth
    env_file:
      - .env
    depends_on:
      - db_auth

volumes:
  db_auth_data: