version: "3.12"
services:

  db:
    container_name: database_neo
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: "12345"
  app:
    build: .
    volumes:
      - .:/config
      - ./static:/app/static
    ports:
      - "8000:8000"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn TravelApp.wsgi:application -w 4 -b 0.0.0.0:8000"

    depends_on:
      - db