version: '3'

services:
  web:
    build: .
    command: python3 manage.py collectstatic --no-input && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/config
      - ./static:/web/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"

volumes:
  postgres_data: