version: "3.12"
services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: "admin"
  app:
    build: .
    volumes:
      - .:/config
      - ./static:/app/static
    ports:
      - "8080:8000"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn TravelApp.wsgi:application -w 4 -b 0.0.0.0:8000"

    depends_on:
      - db