# Generated by Django 5.0.2 on 2024-02-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0006_user_phone_number'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
