# Generated by Django 5.0.2 on 2024-02-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0008_user_alter_review_user_delete_customuser'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
